#!/usr/bin/env php
<?php

error_reporting(E_ERROR);

// composer autoloader
require_once __DIR__ . '/vendor/autoload.php';

// Require composer autoloader and load libraries
use SaschaEnde\Easydoctor\Arguments;
use SaschaEnde\Easydoctor\Easydoctor;
use SaschaEnde\Easydoctor\Exporter;

Arguments::getArguments();

// call the doctor
$doctor = new Easydoctor();
$doctor->printOutput("you called the doctor, welcome...");

// call exporter
$exporter = new Exporter();

// checks
if(empty(Arguments::get('p'))){
    echo 'error: please define a project. Syntax: php easydoctor projectname';
    exit;
}

// scan documentation dir
$docFiles = $doctor->scandir('doc/'.Arguments::get('p'));

// load the pages now
$pagenum = 1;
foreach($docFiles as $filename){
    $fileContents = file_get_contents('doc/'.Arguments::get('p').'/'.$filename);
    $doctor->addToContentList($fileContents,$pagenum);
    $fileContents = $doctor->renderProgrammingCode($fileContents);
    $exporter->addPage($fileContents);
    $pagenum++;
}

// Generate the contents list
$exporter->setContents($doctor->renderContentList());

// Finally render
$exporter->render();

// success
$doctor->printOutput("thanks, the documentation was rendered");