#!/usr/bin/env php
<?php

error_reporting(E_ERROR);

// composer autoloader
require_once '../vendor/autoload.php';

$mpdf = new \mPDF();
$html = file_get_contents('dotleaders.html');
$mpdf->WriteHTML($html);
$mpdf->Output('dotleaders.pdf', 'F');